#!/usr/bin/env python3
"""Regenerate the enlarged copy of peon-ping's macOS overlay.

peon-ping hard-codes the banner geometry, so this re-applies the size patch to
whatever version Homebrew currently ships. Run it after `brew upgrade
peon-ping`; it refuses to write anything if upstream changed the lines it
patches, rather than emitting a half-patched overlay.
"""

import sys
from pathlib import Path

SOURCE_CANDIDATES = (
    Path("/opt/homebrew/opt/peon-ping/libexec/scripts/mac-overlay.js"),
    Path("/usr/local/opt/peon-ping/libexec/scripts/mac-overlay.js"),
)
TARGET = Path("~/.cursor/peon-extras/mac-overlay-large.js").expanduser()
HEADER = (
    "// Generated by ~/.cursor/peon-extras/build-large-overlay.py from\n"
    "// {source}\n"
    "// Do not edit by hand; edit the generator and re-run it.\n"
)

REPLACEMENTS = (
    ("var winWidth = 500, winHeight = 80;", "var winWidth = 650, winHeight = 100;"),
    ("var iconSize = 60;", "var iconSize = 72;"),
    (
        "var titleFont = $.NSFont.boldSystemFontOfSize(16);",
        "var titleFont = $.NSFont.boldSystemFontOfSize(18);",
    ),
    (
        "var subFont = $.NSFont.systemFontOfSize(12);",
        "var subFont = $.NSFont.systemFontOfSize(14);",
    ),
    ("var gap = 2;", "var gap = 10;"),
    # Breathing room between the pack icon and the text block.
    ("textX = 10 + iconSize + 5;", "textX = 10 + iconSize + 16;"),
    # Left-align both rows so the title and excerpt share an edge beside the icon.
    (
        "label.setAlignment($.NSTextAlignmentCenter);",
        "label.setAlignment($.NSTextAlignmentLeft);",
    ),
    (
        "subLabel.setAlignment($.NSTextAlignmentCenter);",
        "subLabel.setAlignment($.NSTextAlignmentLeft);",
    ),
)


def find_source():
    return next((path for path in SOURCE_CANDIDATES if path.is_file()), None)


def patch(source_text):
    patched = source_text
    for old, new in REPLACEMENTS:
        found = patched.count(old)
        if found != 1:
            raise SystemExit(
                "Upstream overlay changed: expected 1 occurrence of {!r}, found {}".format(
                    old, found
                )
            )
        patched = patched.replace(old, new)
    return patched


def main():
    source = find_source()
    if source is None:
        raise SystemExit("packaged mac-overlay.js not found; is peon-ping installed?")

    patched = patch(source.read_text())
    shebang, _, body = patched.partition("\n")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "{}\n{}{}".format(shebang, HEADER.format(source=source), body)
    )
    TARGET.chmod(0o755)

    print("source: {}".format(source))
    print("target: {}".format(TARGET))
    for old, new in REPLACEMENTS:
        print("  {} -> {}".format(old, new))
    return 0


if __name__ == "__main__":
    sys.exit(main())
